package STOCK;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class homee extends javax.swing.JFrame {

    /**
     * Creates new form homee
     */
    public homee() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        

setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ppu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lout = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        item = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        st = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("HOME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 50, 120, 51);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/billingcart.png"))); // NOI18N
        jButton2.setText("ADD STOCK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 620, 140, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/rsz_1rsz_updt.jpg"))); // NOI18N
        jButton4.setText("UPDATE STOCK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(780, 620, 183, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/billingcart.png"))); // NOI18N
        jButton5.setText("BILL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1010, 620, 123, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 370, 60, 30);

        name.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(name);
        name.setBounds(650, 370, 300, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 430, 85, 42);

        qty.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(qty);
        qty.setBounds(680, 430, 87, 40);

        pid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(pid);
        pid.setBounds(1100, 380, 110, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Product ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(960, 370, 130, 34);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(960, 430, 99, 38);

        ppu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(ppu);
        ppu.setBounds(1100, 430, 74, 42);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Logged in as: admin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 42, 147, 32);

        lout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/logout.png"))); // NOI18N
        lout.setText("Logout");
        lout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutActionPerformed(evt);
            }
        });
        getContentPane().add(lout);
        lout.setBounds(20, 100, 150, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/regstr.png"))); // NOI18N
        jButton3.setText("Register ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 100, 160, 50);

        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemKeyTyped(evt);
            }
        });
        getContentPane().add(item);
        item.setBounds(570, 120, 502, 38);

        st.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name"
            }
        ));
        st.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(st);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(590, 190, 450, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\NK\\src\\STOCK\\bbbccckk.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        homepage h=new homepage();
        h.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        update u= new update();
        u.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        Add_stock a=new Add_stock();
        a.setVisible(true);
         this.dispose();
        
      // DefaultTableModel model=(DefaultTableModel) T1.getModel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutActionPerformed
        // TODO add your handling code here:
        loginpage l=new loginpage();
        l.setVisible(true);
        empbill e=new empbill();
        e.dispose();
    }//GEN-LAST:event_loutActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Register r=new Register();
        r.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemActionPerformed

    private void itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemKeyReleased
        // TODO add your handling code here:
        st.setVisible(true);
        int i=0;
        char c=evt.getKeyChar();

        DefaultTableModel model=(DefaultTableModel) st.getModel();
        if(item.getText().trim().equals(""))
        {
            while(i<model.getRowCount())
            model.removeRow(i);}
        if(c==KeyEvent.VK_BACK_SPACE)
        {
            while(i<model.getRowCount())
            model.removeRow(i);

            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
                PreparedStatement pp=con.prepareStatement("select name from stock where name like ?");
                pp.setString(1,item.getText()+"%");
                ResultSet rs=pp.executeQuery();
                while(rs.next())
                {
                    model.addRow(new Object[] {rs.getString("name")});
                }
            }catch(Exception e){}
        }
        else
        try
        {

            while(i<model.getRowCount())
            model.removeRow(i);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
            PreparedStatement p=con.prepareStatement("select name from stock where name like ?");
            p.setString(1,item.getText()+"%");
            ResultSet rs=p.executeQuery();
            
            if(rs.equals(0))
            JOptionPane.showMessageDialog(null, "Enter a Valid Name");

            else{
                while(rs.next())
                {
                   
                    model.addRow(new Object[] {rs.getString("name")});
                }
                
            }
            rs.close();
            p.close();
            con.close();
        }
        catch(SQLException e)
        { }
        catch(ClassNotFoundException e)
        {}
        catch(Exception e)
        {}

    }//GEN-LAST:event_itemKeyReleased

    private void itemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(ch==KeyEvent.VK_ENTER)
        {

            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
                PreparedStatement ps=con.prepareStatement("select * from stock where name =?");
                ps.setString(1, item.getText());
                ResultSet rs=ps.executeQuery();

                if(rs.wasNull())
                JOptionPane.showMessageDialog(null, "Medicine not avaiable");
                while(rs.next())
                {
                    name.setText(rs.getString("name"));
                    pid.setText(rs.getString("pid"));
                    qty.setText(rs.getString("qty"));
                    ppu.setText(rs.getString("price"));
                }

            }
            catch(SQLException e){}
            catch(ClassNotFoundException e){}
        }
    }//GEN-LAST:event_itemKeyTyped

    private void stMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) st.getModel();
        int i=st.getSelectedRow();
        String s=((String) model.getValueAt(st.getSelectedRow(), 0));
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
            PreparedStatement p=con.prepareStatement("select * from stock where name=?");
            p.setString(1, s);
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
               
                item.setText(rs.getString("name"));
                name.setText(rs.getString("name"));
                ppu.setText(rs.getString("price"));
                qty.setText(rs.getString("qty"));
                pid.setText(rs.getString("pid"));
                model.removeRow(st.getSelectedRow());
            }

        }
        catch(SQLException e)
        {System.out.println("Inside SQL");
            e.printStackTrace();}
        catch(ClassNotFoundException e)
        {System.out.println("Inside ClassNotFound");}
        catch(Exception e){System.out.println("Inside Exception");

        }
    }//GEN-LAST:event_stMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField item;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lout;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pid;
    private javax.swing.JLabel ppu;
    private javax.swing.JLabel qty;
    private javax.swing.JTable st;
    // End of variables declaration//GEN-END:variables
}
