package STOCK;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

setVisible(true);
        
        t2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ppu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        updt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        del = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Product Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 30));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 210, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Product ID");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 30));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 220, 120, 20);

        ppu.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ppu.setMaximumSize(new java.awt.Dimension(50, 30));
        ppu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppuActionPerformed(evt);
            }
        });
        ppu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ppuKeyTyped(evt);
            }
        });
        getContentPane().add(ppu);
        ppu.setBounds(840, 270, 130, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Price Per Unit");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 30));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 280, 120, 20);

        item.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item.setMaximumSize(new java.awt.Dimension(50, 30));
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemKeyTyped(evt);
            }
        });
        getContentPane().add(item);
        item.setBounds(470, 210, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Quantity");
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 30));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 360, 90, 20);

        qty.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        qty.setMaximumSize(new java.awt.Dimension(50, 30));
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(840, 350, 130, 40);

        updt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/updat.png"))); // NOI18N
        updt.setText("UPDATE");
        updt.setMaximumSize(new java.awt.Dimension(50, 30));
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        getContentPane().add(updt);
        updt.setBounds(350, 560, 180, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel5.setText("UPDATE STOCK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 10, 260, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/homeick.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 60, 80, 60);

        jScrollPane4.setMaximumSize(new java.awt.Dimension(50, 30));

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t2.setColumnSelectionAllowed(true);
        t2.getTableHeader().setReorderingAllowed(false);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(t2);
        t2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(470, 250, 160, 110);

        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/deleteick.png"))); // NOI18N
        del.setText("DELETE");
        del.setMaximumSize(new java.awt.Dimension(50, 30));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(610, 560, 180, 60);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/resetick.png"))); // NOI18N
        jButton3.setText("RESET");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(840, 560, 190, 60);

        pid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(pid);
        pid.setBounds(840, 220, 100, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STOCK/bbbccckk.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel model=(DefaultTableModel) T1.getModel();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
            PreparedStatement p=con.prepareStatement("update stock set pid=?,qty=?,price=?,name=? where pid=?");
            p.setString(1,pid.getText());
            p.setInt(2, Integer.parseInt(qty.getText()));
            p.setFloat(3,Float.parseFloat(ppu.getText()));
            p.setString(4, item.getText());
            p.setString(5, pid.getText());
            p.executeUpdate();
            item.setText("");
            qty.setText("");
            ppu.setText("");
            pid.setText("");
            JOptionPane.showMessageDialog(null, "UPDATED!");

            con.close();
        }
    catch(SQLException e)
    { }
catch(ClassNotFoundException e)
    {}
    }//GEN-LAST:event_updtActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_itemActionPerformed

    private void itemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemKeyTyped
        // TODO add your handling code here:
      //  DefaultTableModel model=(DefaultTableModel) T1.getModel();
        char st=evt.getKeyChar();
        if(st==KeyEvent.VK_ENTER)
{

    try
    {
        if(item.getText().trim().equals(""))
        JOptionPane.showMessageDialog(null, "Please Enter the Product Name!");

        else

               try
                    {

                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
                        PreparedStatement p=con.prepareStatement("select * from stock where name=?");
                        p.setString(1, item.getText());
                        ResultSet rs=p.executeQuery();
                        if(rs.equals(0))
                        {
                         JOptionPane.showMessageDialog(null, "Enter a Valid Name");
                        }
                        else{
                        while(rs.next())
                        {
                            
                            pid.setText(rs.getString("pid"));
                            qty.setText(rs.getString("qty"));
                            ppu.setText(rs.getString("price"));
                        }
                        }
                        rs.close();
                        p.close();
                        con.close();

                    }
                catch(SQLException e)
                    { }
                catch(ClassNotFoundException e)
                    {}

                            }


                catch(Exception e){}



}
        char ch=evt.getKeyChar();
        DefaultTableModel model=(DefaultTableModel) t2.getModel();
          
    }//GEN-LAST:event_itemKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        homee h=new homee();
        h.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemKeyReleased
        // TODO add your handling code here:
        t2.setVisible(true);
        int i=0;
        char c=evt.getKeyChar();

        DefaultTableModel model=(DefaultTableModel) t2.getModel();
        if(item.getText().trim().equals(""))
        {
        while(i<model.getRowCount())
            model.removeRow(i);}
        if(c==KeyEvent.VK_BACK_SPACE)
        {
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
            PreparedStatement pp=con.prepareStatement("select name from stock where name like ?");
            pp.setString(1,item.getText()+"%");
            ResultSet rs=pp.executeQuery();
            while(rs.next())
            {
                model.addRow(new Object[] {rs.getString("name")});

            }
        }catch(Exception e){}
        }
        else
        try
        {
            
        
          while(i<model.getRowCount())
            model.removeRow(i);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
            PreparedStatement p=con.prepareStatement("select name from stock where name like ?");
            p.setString(1,item.getText()+"%");
            ResultSet rs=p.executeQuery();
           if(rs.equals(0))
                JOptionPane.showMessageDialog(null, "Enter a Valid Name");

            else{
            while(rs.next())
            {
                
                model.addRow(new Object[] {rs.getString("name")});
            }
           
            }
            rs.close();
            p.close();
            con.close();
        }
        catch(SQLException e)
        { }
        catch(ClassNotFoundException e)
        {}
        catch(Exception e)
        {}
    }//GEN-LAST:event_itemKeyReleased

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        // TODO add your handling code here:
        {
        DefaultTableModel model=(DefaultTableModel) t2.getModel();
        int i=t2.getSelectedRow();
        String s=((String) model.getValueAt(t2.getSelectedRow(), 0));
        try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
                    PreparedStatement p=con.prepareStatement("select * from stock where name=?");
                    p.setString(1, s);
                    ResultSet rs=p.executeQuery();
                    while(rs.next())
                        {
                           
                            pid.setText(rs.getString("pid"));
                            item.setText(rs.getString("name"));
                            qty.setText(rs.getString("qty"));
                            ppu.setText(rs.getString("price"));
                            model.removeRow(t2.getSelectedRow());
                        }

                }
            catch(SQLException e)
                {System.out.println("Inside SQL");
                e.printStackTrace();}
            catch(ClassNotFoundException e)
                {System.out.println("Inside ClassNotFound");}
            catch(Exception e){System.out.println("Inside Exception");

            }
    }
    }//GEN-LAST:event_t2MouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        if(item.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select a product name to delete");
        }
        else{
       int ch= JOptionPane.showConfirmDialog(null, "Do you want to delete?");
        if(ch==0)
        {
            try
                {

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
                    PreparedStatement p=con.prepareStatement("delete from stock where pid=?");
                    p.setString(1,pid.getText());
                    p.executeUpdate();

JOptionPane.showMessageDialog(null, "Deleted");
                      item.setText("");
                qty.setText("");
                ppu.setText("");
               pid.setText("");


                }
            catch(SQLException e)
                {System.out.println("Inside SQL");
                e.printStackTrace();}
            catch(ClassNotFoundException e)
                {System.out.println("Inside ClassNotFound");}
        }
        else
        {
            item.setText("");
                qty.setText("");
                ppu.setText("");
               pid.setText("");

        }

        }
    }//GEN-LAST:event_delActionPerformed

    private void ppuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        item.setText("");
                qty.setText("");
                ppu.setText("");
               pid.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        // TODO add your handling code here:
        char ch= evt.getKeyChar();
        if(Character.isDigit(ch))
        {}
        else
            evt.consume();
    }//GEN-LAST:event_qtyKeyTyped

    private void ppuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppuKeyTyped
        // TODO add your handling code here:
        char st = evt.getKeyChar();

            if (Character.isDigit(st) || (st == 46)) {}
            else
                evt.consume();
    }//GEN-LAST:event_ppuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JTextField item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField ppu;
    private javax.swing.JTextField qty;
    private javax.swing.JTable t2;
    private javax.swing.JButton updt;
    // End of variables declaration//GEN-END:variables
}
