import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public Float total;
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalqty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ppu = new javax.swing.JTextField();
        del = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Item Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 150, 90, 40);
        getContentPane().add(item);
        item.setBounds(490, 150, 560, 40);

        jLabel2.setText("Total Stock");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 220, 120, 40);
        getContentPane().add(totalqty);
        totalqty.setBounds(490, 220, 90, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("INVOICE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 50, 150, 70);

        jLabel4.setText("Price Per Unit");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, 220, 110, 40);
        getContentPane().add(ppu);
        ppu.setBounds(900, 220, 130, 40);

        del.setText("DELETE");
        del.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(940, 350, 90, 30);

        ad.setText("ADD");
        ad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        getContentPane().add(ad);
        ad.setBounds(650, 350, 90, 30);

        jLabel6.setText("Quantity Required");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 280, 140, 40);

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(490, 280, 90, 40);

        jButton3.setText("Update Stock");
        getContentPane().add(jButton3);
        jButton3.setBounds(90, 10, 120, 40);

        jButton4.setText("Generate Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(200, 10, 110, 40);

        jButton5.setText("Add Stock");
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 10, 90, 40);

        jButton6.setText("Generate Bill");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(750, 630, 77, 21);

        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(800, 350, 79, 30);

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quanity", "Price"
            }
        ));
        T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(T1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(470, 410, 600, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) T1.getModel();
        
        if(!(item.getText().trim().equals("")&&qty.getText().trim().equals("")))
        {
            String a=ppu.getText();
            String b=qty.getText();
            Float a1=Float.parseFloat(a);
            Float b1=Float.parseFloat(b);
            total=a1*b1;
             //price(total);
            model.addRow(new Object[]{ item.getText(),qty.getText(),total});
        item.setText("");
        totalqty.setText("");
        qty.setText("");
        ppu.setText("");
    }//GEN-LAST:event_adActionPerformed
        else
        {
            JOptionPane.showMessageDialog(null,"Field cannot be left blank");
        }
    }
    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) T1.getModel();
        if(T1.getSelectedRow()==-1)
          if(T1.getRowCount()==0)
                JOptionPane.showMessageDialog(null,"Table is empty");
        else
                JOptionPane.showMessageDialog(null,"Select any Entry");
        else
        model.removeRow(T1.getSelectedRow());
      item.setText("");
        totalqty.setText("");
        qty.setText("");
       ppu.setText("");
    }//GEN-LAST:event_delActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) T1.getModel();
        if(T1.getSelectedRow()==-1)
          if(T1.getRowCount()==0)
                JOptionPane.showMessageDialog(null,"Table is empty");
          else
                JOptionPane.showMessageDialog(null,"Select any row");
        
        else
        {
        model.setValueAt(item.getText(),T1.getSelectedRow() , 0);
         model.setValueAt(qty.getText(),T1.getSelectedRow() , 1);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void T1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) T1.getModel();
        item.setText(model.getValueAt(T1.getSelectedRow(), 0).toString());
        ppu.setText(model.getValueAt(T1.getSelectedRow(), 1).toString());
        qty.setText(model.getValueAt(T1.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_T1MouseClicked

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_qtyKeyPressed

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_qtyKeyReleased

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T1;
    private javax.swing.JButton ad;
    private javax.swing.JButton del;
    private javax.swing.JTextField item;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ppu;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField totalqty;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
